language: python
python:
- 3.6
cache:
  pip: true
  directories:
  - node_modules
script:
- npm install
- node node_modules/gulp/bin/gulp.js build-production
notifications:
  email:
  - estep@esciencecenter.nl
