language: python
python:
- 3.6
cache:
  pip: true
  directories:
  - node_modules
script:
- npm install
- node node_modules/gulp/bin/gulp.js build-production
- pip install py-w3c==0.3.1 pytest requests_mock
- PYTHONPATH=. pytest
notifications:
  email:
  - estep@esciencecenter.nl
