version: '2'

services:
  node-sass:
    container_name: node-sass
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    volumes:
      - ./static:/static
      - ./style:/style
      - ./scripts:/scripts

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - node-sass
    environment:
      - FLASK_APP=/app/app/application.py
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"

