version: '3'

services:
  mongo:
    image: "mongo:3.6"
    volumes:
      - ./docker-volumes/db:/data/db
      - ./config/mongo.sh:/mongo.sh
      - ./docker-volumes/db-init:/db-init
    entrypoint: /mongo.sh
    command: --bind_ip 0.0.0.0
    container_name: rsd-database

  auth:
    build:
      context: ./auth-github
    container_name: rsd-admin-authentication
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    container_name: rsd-backend
    env_file:
      - .env
    depends_on:
      - mongo

  admin:
    container_name: rsd-admin
    volumes:
      - rsd_static_admin:/build
    command: sh -c "rm -rf /build/* && cp -r /usr/share/nginx/html/* /build"

  frontend:
    build:
      context: ./frontend
    container_name: rsd-frontend
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - rsd_static_frontend:/shared_static
      - ./docker-volumes/oaipmh-cache:/static/oaipmh-cache

  tasks:
    build:
      context: ./tasks
    container_name: rsd-tasks
    env_file:
      - .env
    depends_on:
      - backend
      - mongo
    volumes:
      - ./docker-volumes/oaipmh-cache:/oaipmh-cache

  nginx_ssl:
    image: rsdnlesc/docker-term-letsencrypt
    container_name: rsd-nginx-ssl
    volumes:
      - ./docker-volumes/cert:/cert
      - ./docker-volumes/letsencrypt:/etc/letsencrypt
    env_file:
      - .env
    restart: unless-stopped

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: rsd-reverse-proxy
    volumes:
      - rsd_static_admin:/static_admin:ro
      - rsd_static_frontend:/static_frontend:ro
    depends_on:
      - frontend
      - backend
      - admin
      - auth
    env_file:
      - .env
    restart: unless-stopped

volumes:
  rsd_static_admin:
  rsd_static_frontend:
