language: python
python:
- 3.6
services:
- docker
- mongodb
cache: pip
install:
- export
- pip install pytest
- pip install pytest-cov
- pip install -r requirements.txt
- pip install coveralls
script:
- PYTHONPATH=`pwd` pytest --cov=src
after_success:
- if [[ $TRAVIS_BRANCH == 'master' ]]; then
    curl -L -X POST https://registry.hub.docker.com/u/rsdnlesc/backend/trigger/$DOCKERHUB_TRIGGER_TOKEN;
  fi
