language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_3dc2464b40f8_key
    -iv $encrypted_3dc2464b40f8_iv 
    -in github_deploy_key.enc 
    -out github_deploy_key 
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - yarn global add greenkeeper-lockfile
install:
  - yarn
before_script: greenkeeper-lockfile-update
script:
  - yarn test && yarn build
after_script: greenkeeper-lockfile-upload
after_success:
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then
    curl -L -X POST https://registry.hub.docker.com/u/rsdnlesc/admin/trigger/$DOCKERHUB_TRIGGER_TOKEN;
    fi
